### ISSUE TITLE
HTML rending of `//additions/list/item`

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#112]
These changes all apply to the following xpath context: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/additions/list/item`
Record example: https://bl.vuexistapps.us/manuscript/10

1. The label for each addition can be constructed similar to the msItems. The folio information can be constructed from `//item/locus/@from`, with the supplied label of "Fol. ":
- Current: "1. (Fol. 1b)"
- New: "Addition 1 (Fol. 1b): "
- Note: some items may not have folio information (i.e., no `//item/locus/@from`), in which case the parentheses should not be included ("Addition 1: "). Other items may have more than one, so for now we will use the first locus in the series, i.e. `//item/locus[1]/@from`

2. We would like to suppress the `//item/label` elements for now

3. Could we increase the space between each addition item, so that it matches the space between each of the msItems in the contents section?

@davidamichelson can you review this issue in case I'm forgetting something?

**Comment by wsalesky** [comment]
Done
