### ISSUE TITLE
Suppress `//msContents/summary` and `//msContents/textLang`

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#113]
Sorry I just caught this (not all data have these elements, so didn't notice it previously). Example record: https://bl.vuexistapps.us/manuscript/403

Could we suppress the following elements:

- `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msContents/summary`
- /TEI/teiHeader/fileDesc/sourceDesc/msDesc/msContents/textLang`

Thanks much!

**Comment by wsalesky** [comment]
Done
