### ISSUE TITLE
Discuss Carets and CSS Border/Vertical Line in Contents/Items

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#114]
![Screen Shot 2023-05-24 at 10 49 51 AM](https://github.com/srophe/britishLibrary/assets/3083773/2291c26c-338c-4a31-9027-a91e2cf05a7c)

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Let me know what you think of this change.

**Comment by wlpotter** [comment]
@wsalesky this looks great! As we mentioned yesterday, we may want to have these borders extend to mimic square brackets if that's feasible. Should I make a separate issue for that?

**Comment by davidamichelson** [comment]
This looks great! Well done with an excellent aesthetic as always. Thank you.
