### ISSUE TITLE
Change border color for physical description, manuscript contents, and additions boxes

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#122]
Could we change the color of the border for the Manuscript Contents box (`//msContents`), so that it is clearly distinguishable from the left borders of each `msItem` element (cf. #114)?

Possibly the blue color of the record title at the top of the page could work? (though we defer to your design skills, @wsalesky )

**Comment by davidamichelson** [comment]
Please make this change for all boxes.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter It would be easier to change the vertical line than the box outline, as the box is a bootstrap component and requires many more style overrides. What do you think?

**Comment by wlpotter** [comment]
@wsalesky changing the vertical line rather than the box outline sounds fine to me. @davidamichelson thoughts?

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Updated. Close if you like it. Otherwise we can make changes.
