### ISSUE TITLE
Translated Title: this box should search by string in all textnodes of TEI:title and TEI:finalRubric in msContents and additions and children of those elements. 

### ISSUE THREAD

**Issue by wsalesky** [srophe/britishLibrary#125]

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter is this only for titles with xml:lang='en' ? Or all titles?

**Comment by davidamichelson** [comment]
> @wsalesky yes, this should just be titles with xml:lang="en"

@wsalesky Actually we changed our mind. Let this just search any TEI:title textnode regardless of @lang, so no need to filter by @lang="en", but for TEI:finalRubric do limit the search to xml:lang="en"

**Comment by davidamichelson** [comment]
Please allow this box to take strings and URIS (search in @ref when a Syriaca URI is the search term).

**Comment by wsalesky** [comment]
@davidamichelson I think this is done, please test.

**Comment by wlpotter** [comment]
Hmm I don't think this is working. I'm not getting any results for a title string, e.g. "hymns", https://bl.vuexistapps.us/search.html?keyword=&author=&title=hymns&syrText=&syrRubricsLimit=true&syrFinalRubricsLimit=true&syrIncipitsLimit=true&syrExplicitsLimit=true&syrColophonsLimit=true&syrOtherLimit=true&place=&person=&locus=

It also raises an error when using a Syriaca work URI, e.g. http://syriaca.org/work/10513 (Search URL: https://bl.vuexistapps.us/search.html?keyword=&author=&title=http%3A%2F%2Fsyriaca.org%2Fwork%2F10513&syrText=&syrRubricsLimit=true&syrFinalRubricsLimit=true&syrIncipitsLimit=true&syrExplicitsLimit=true&syrColophonsLimit=true&syrOtherLimit=true&place=&person=&locus=)

**Comment by wsalesky** [comment]
fixed
