### ISSUE TITLE
Manuscript record https://bl.vuexistapps.us/manuscript/336 throwing an app error

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#132]
@wsalesky I am getting an app error when trying to load this record: https://bl.vuexistapps.us/manuscript/336.

It is likely a data error, since it only appears to occur with this record; however, I can't tell what part of the data might be causing this error. Would you mind taking a look at the error message to see if you can determine what the issue might be?

If it turns out to be a data issue, feel free to assign back to me to address. Thanks much!

**Comment by wsalesky** [comment]
This is causing the error: 
https://github.com/srophe/britishLibrary-data/blob/main/data/tei/336.xml#L527

I will change the code so it tests for a number.
