### ISSUE TITLE
Manuscript Contents Section: Move tei:Author and tei:Title up to first line

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#133]
In the new indented layout for MS Contents (see issue #122) the contents of tei:Author and tei:Title inside tei:msItem were pushed to the second line of the item (first indented line). See this example: items 11-13 here https://bl.vuexistapps.us/manuscript/10
<img width="1127" alt="Screen Shot 2023-06-07 at 10 49 31 AM" src="https://github.com/srophe/britishLibrary/assets/3083773/1d0dc57c-abe5-4290-b444-4bf68e2c4010">

Please move the contents of tei:Author and tei:Title back to be on the same line as "Item # (Fol. #)". so that it is on the first line and not indented. Keep the indent and new line for everything else. (indent is signified here using I> since I can't get indent to work in the mark down)

Current:
**Item 11 (Fol. 124b):**
[The Psalms](https://bl.vuexistapps.us/search.html?ref=http://syriaca.org/work/9672)
I>Title: ܬܘܼܒ ܫܡܵܗܐ: ܕܡ̣ܢ ܟܬܵܒ݂ܐ: ܕܡܲܙܡܘܿܪ̈ܐ: ܕܛܘ݂ܒ݂ܢܐ: ܕܵܘܝ̣ܕ: ܟ݂ܕ ܪܵܫܡܝ̣ܢܲܢ: ܐܦ ܥܸܠܲܠܬ݂ܗܘܿܢ: ܕܡܲܙܡܘܿܪ̈ܐ܇ ܦܵܣܝ̣ܩܵܐܝ̣ܬ
I>Excerpt: ܏ܬܘܼܒ: ܏ܫܵܡܗ̈ܐ: ܕ܏ܡ̣ܢ ܏ܟܬܵܒ݂ܐ: ܕܡܲܙ܏ܡܘܿܪ̈ܐ: ܏ܕܛܘܼܒܢܵܐ: ܕܵܘ܏ܝ̣ܕ: ܏ܟ݂ܕ ܪܵܫ܏ܡܝ̣ܢܲܢ: ܏ܐܦ ܏ܥܸܠܲܠܬ݂ܗܘܿܢ: ܕܡܲܙ܏ܡܘܿܪ̈ܐ: ܏ܦܵܣܝ̣ܩܵܐܝ̣ܬ. ܕܚܕܐ ܏ܡܲܪܬ݁ܝܢܘܼܬ݂ܵܐ ܏ܡܪ܀ ܐ܀ ܛܘܼܒܘܗܝ ܠܓܲܒܼܪܐ ܕܒܐܘ̣ܪܚܵܐ ܕܥ̇ܘ̈ܠܐ ܠܐ ܗܲܠܸܟ̇. ܘܲܒܪܹܥܝܢܵܐ ܕܚ̈ܛܝܹܐ ܠܐ ܩܵܡ̇. ܘܥܲܠ ܡܵܘܬ݁ܒ̣ܵܐ ܕܲܡܡܲܝ̈ܩܢܹܐ ܠܐ ܝ̣ܬ݂ܸܒ܇ ܐܠ̣ܐ ܒܢܵܡܘܿܣܹܗ ܕܡܪܝܐ ܨܹܒ݂ܝܵܢܗ.. ܕܦܹܐܪ̈ܘܗܝ ܝܗ̇ܒ ܒܙܲܒ̣ܢܹܗ ܘܛ̇ܪ̈ܦܘܗܝ ܠܐ ܢܵܬܪܝ̣ܢ. ܐܝܟ.ܐ ܘܟܠ ܕܥ̇ܒܕ ܡܫܲܠܸܡ ܘ. ܐܠ̣ܐ̣ ܐܲܝܟ ܥܘܼܪܵܐ ܕܕ̣ܵܪܝܵܐ ܪܘܼܚܐ. ܡܛܠ ܕܝܵܕ̣ܥ ܗ̇ܘܼ ܡܪܝܐ ܐܘܼܪܚܵܐ ܕܙܲܕܝ̣ܩ̈ܐ. ܘܐܘܼܪܚܵܐ ܕܪ̈ܫܝܥܐ ܬ̣ܹܐܒܲܕ݂.
I>Note: The following Psalms are inscribed ܥܠ ܡܩܒܝ̈ܐ, “concerning the Maccabees,” 47, 56, 57, 58, 59, 60, 62, 69, 74, 79, 80, 83, 108, and 109. Ps. 143 inscribed ܬܘܕܝܬܐ ܕܡܩܒܝ̈ܐ. See Add 17,110.
**Item 12 (Fol. 143b):**
I>[Solomon](https://bl.vuexistapps.us/browse.html?view=author&ref=http://syriaca.org/person/3571). [The Proverbs of Solomon](https://bl.vuexistapps.us/search.html?ref=http://syriaca.org/work/9623)
I>Title: ܬܘܼܒ݂ ܫ̈ܡܵܗܸܐ ܘܲܩܪ̈ܵܝܵܬ݂ܵܐ: ܕܡ̣ܢ ܟܬ݂ܵܒ݂ܵܐ ܕܚܟ݂ܡܬ݂ܵܐ ܕܲܫܠܹܝܡܘܿܢ.
**Item 13 (Fol. 150a):**
I>Jesus the son of Sirach. Ecclesiasticus, or the Wisdom of Jesus the son of Sirach
I>Title: ܬܘܼܒ݂ ܫܡܵܗܸ̈ܐ ܘܲܩܪ̈ܵܝܵܬ݂ܵܐ ܕܡ̣ܢ ܚܟ݂ܡܬ݂ܵܐ ܕܒ݁ܪܣܝ̣ܪܵܐ 

New:
**Item 11 (Fol. 124b):** [The Psalms](https://bl.vuexistapps.us/search.html?ref=http://syriaca.org/work/9672)
I>Title: ܬܘܼܒ ܫܡܵܗܐ: ܕܡ̣ܢ ܟܬܵܒ݂ܐ: ܕܡܲܙܡܘܿܪ̈ܐ: ܕܛܘ݂ܒ݂ܢܐ: ܕܵܘܝ̣ܕ: ܟ݂ܕ ܪܵܫܡܝ̣ܢܲܢ: ܐܦ ܥܸܠܲܠܬ݂ܗܘܿܢ: ܕܡܲܙܡܘܿܪ̈ܐ܇ ܦܵܣܝ̣ܩܵܐܝ̣ܬ
I>Excerpt: ܏ܬܘܼܒ: ܏ܫܵܡܗ̈ܐ: ܕ܏ܡ̣ܢ ܏ܟܬܵܒ݂ܐ: ܕܡܲܙ܏ܡܘܿܪ̈ܐ: ܏ܕܛܘܼܒܢܵܐ: ܕܵܘ܏ܝ̣ܕ: ܏ܟ݂ܕ ܪܵܫ܏ܡܝ̣ܢܲܢ: ܏ܐܦ ܏ܥܸܠܲܠܬ݂ܗܘܿܢ: ܕܡܲܙ܏ܡܘܿܪ̈ܐ: ܏ܦܵܣܝ̣ܩܵܐܝ̣ܬ. ܕܚܕܐ ܏ܡܲܪܬ݁ܝܢܘܼܬ݂ܵܐ ܏ܡܪ܀ ܐ܀ ܛܘܼܒܘܗܝ ܠܓܲܒܼܪܐ ܕܒܐܘ̣ܪܚܵܐ ܕܥ̇ܘ̈ܠܐ ܠܐ ܗܲܠܸܟ̇. ܘܲܒܪܹܥܝܢܵܐ ܕܚ̈ܛܝܹܐ ܠܐ ܩܵܡ̇. ܘܥܲܠ ܡܵܘܬ݁ܒ̣ܵܐ ܕܲܡܡܲܝ̈ܩܢܹܐ ܠܐ ܝ̣ܬ݂ܸܒ܇ ܐܠ̣ܐ ܒܢܵܡܘܿܣܹܗ ܕܡܪܝܐ ܨܹܒ݂ܝܵܢܗ.. ܕܦܹܐܪ̈ܘܗܝ ܝܗ̇ܒ ܒܙܲܒ̣ܢܹܗ ܘܛ̇ܪ̈ܦܘܗܝ ܠܐ ܢܵܬܪܝ̣ܢ. ܐܝܟ.ܐ ܘܟܠ ܕܥ̇ܒܕ ܡܫܲܠܸܡ ܘ. ܐܠ̣ܐ̣ ܐܲܝܟ ܥܘܼܪܵܐ ܕܕ̣ܵܪܝܵܐ ܪܘܼܚܐ. ܡܛܠ ܕܝܵܕ̣ܥ ܗ̇ܘܼ ܡܪܝܐ ܐܘܼܪܚܵܐ ܕܙܲܕܝ̣ܩ̈ܐ. ܘܐܘܼܪܚܵܐ ܕܪ̈ܫܝܥܐ ܬ̣ܹܐܒܲܕ݂.
I>Note: The following Psalms are inscribed ܥܠ ܡܩܒܝ̈ܐ, “concerning the Maccabees,” 47, 56, 57, 58, 59, 60, 62, 69, 74, 79, 80, 83, 108, and 109. Ps. 143 inscribed ܬܘܕܝܬܐ ܕܡܩܒܝ̈ܐ. See Add 17,110.
**Item 12 (Fol. 143b):** [Solomon](https://bl.vuexistapps.us/browse.html?view=author&ref=http://syriaca.org/person/3571). [The Proverbs of Solomon](https://bl.vuexistapps.us/search.html?ref=http://syriaca.org/work/9623)
I>Title: ܬܘܼܒ݂ ܫ̈ܡܵܗܸܐ ܘܲܩܪ̈ܵܝܵܬ݂ܵܐ: ܕܡ̣ܢ ܟܬ݂ܵܒ݂ܵܐ ܕܚܟ݂ܡܬ݂ܵܐ ܕܲܫܠܹܝܡܘܿܢ.
**Item 13 (Fol. 150a):** Jesus the son of Sirach. Ecclesiasticus, or the Wisdom of Jesus the son of Sirach
I>Title: ܬܘܼܒ݂ ܫܡܵܗܸ̈ܐ ܘܲܩܪ̈ܵܝܵܬ݂ܵܐ ܕܡ̣ܢ ܚܟ݂ܡܬ݂ܵܐ ܕܒ݁ܪܣܝ̣ܪܵܐ

**Comment by wsalesky** [comment]
done
