### ISSUE TITLE
`//msItem/note` element should precede any child `msItem` elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#134]
Example record: https://bl.vuexistapps.us/manuscript/10

`msItem/note` elements are currently being displayed following any child `msItem` elements. In the example record, for instance, the tei:note elements in item 1 (`//msItem[xml:id="a1"]`) follow the child items 2-30. These four note elements should be displayed before any child `msItem` elements.

Child `msItem` elements should always be the last elements in the sequence

This may have changed with updates in #122

**Comment by wsalesky** [comment]
done
