### ISSUE TITLE
Syriac Text: this box should search by string in all textnodes of the paths defined below

### ISSUE THREAD

**Issue by wsalesky** [srophe/britishLibrary#140]

**Comment by davidamichelson** [comment]
This box does not need to take URIS (yet).

**Comment by davidamichelson** [comment]
Update to this item:

We would like this search box to have below it a series of check boxes for limiting by path.

labels: "Search In: [] Titles/Rubrics [] Final Rubrics/Subscriptions [] Incipits [] Explicits/Desinits [] Colophons [] Other"

By default all should be checked. If unchecked then limit searches above to these paths:

[] Titles/Rubrics = TEI:rubric and TEI:title[xml:Lang="syr"]
[] Final Rubrics/Subscriptions = TEI:finalRubric 
[] Incipits = TEI:incipit
[] Explicits/Desinits = TEI:explicit
[] Colophons = /TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/additions/list/item[label["Colophon"]] (ie search in item (and children) where item has child with label with textnode "Colophon")
[] Other = TEI:quote [xml:Lang="syr"] or TEI:foreign [xml:Lang="syr"]

**Comment by davidamichelson** [comment]
- [ ] Related clean up item, we need to find other places where xml:Lang="syr" and clean them up.

**Comment by wsalesky** [comment]
@wlpotter how does it look  now?
