### ISSUE TITLE
HTML visualization for multi-part manuscripts: Change Ms Part label

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#144]
This issue begins the visualization requests for records that have tei:msPart elements.
Model record: https://bl.vuexistapps.us/manuscript/1

The box currently labeled "Ms Part 1" should instead be labelled based on 
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/msIdentifier/altIdentifier/idno/@type="BL-Shelfmark"

So in this case the label would change from 

Current:
Ms Part 1

Revised:
Add. 12,133, foll. 1–108

**Comment by davidamichelson** [comment]
Please go ahead with this: This is app version 2.09

**Comment by wsalesky** [comment]
@davidamichelson Is this for multi-part manuscripts only? Or for all manuscripts?

**Comment by davidamichelson** [comment]
This is for for multi-part manuscripts only (as discussed in meeting)

**Comment by wsalesky** [comment]
Done
