### ISSUE TITLE
Remove "Manuscript Contents" box and label for multi-part manuscripts

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#145]
This is a visualization request for records that have tei:msPart elements.
Model record: https://bl.vuexistapps.us/manuscript/1

**This change is for multipart records only.** We want this feature to remain for records that do not have msPart. Let's discuss since this may mean rewriting code.

**Comment by davidamichelson** [comment]
Please go ahead with this: This is app version 2.09

**Comment by wsalesky** [comment]
@davidamichelson Can you look at the current iteration and let me know how you want it to be changed? Thanks.

**Comment by davidamichelson** [comment]
This looks good, some spacing looks odd but may be unrelated. I will make a separate issue. Thanks!
