### ISSUE TITLE
Change font to bold for tei:Locus on tei:Addition

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#149]
Currently in msItems the number and the locus are in bold. For Additions only the addition number but not the locus (fol. 4.) are bold. Please place the locus and parentheses and colon in bold.

Current:
**Addition 1** (Fol. 1b):

New:
**Addition 1 (Fol. 1b):**

**Comment by wsalesky** [comment]
@davidamichelson I think this has been done?
