### ISSUE TITLE
For each MSpart in a multi part ms please create the same sort of introductory section as in a single part MS 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#152]
BUT the difference is that the single part ms section is from msDesc+ descendents while the multipart is from msPart+ descendants. (Note the descendant elements are the same).

This is complicated, we can discuss in person. Please compare manuscript/1 and manuscript/10

This is a visualization request for records that have tei:msPart elements.
Model record: https://bl.vuexistapps.us/manuscript/1
This is app version 2.09

**Comment by davidamichelson** [comment]
Please reuse as much of the same css and xquery as you did for the single part MS so we can change these together if needed.

**Comment by wsalesky** [comment]
done
