### ISSUE TITLE
Please format tei:note contents in multipart MS using the same style as for singlepart MS

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#154]
ie. please add bulleted lines, spacing, and also fix missing whitespace

Compare manuscript/1 and manuscript/10

This is a visualization request for records that have tei:msPart elements.
Model record: https://bl.vuexistapps.us/manuscript/1
This is app version 2.09

**Comment by davidamichelson** [comment]
See manuscript/1 Part 2 Item 3 for an example note

**Comment by davidamichelson** [comment]
Not yet, please add bullet points:
https://bl.vuexistapps.us/manuscript/10 (has bullets)
https://bl.vuexistapps.us/manuscript/1 (needs bullets)

**Comment by wsalesky** [comment]
@davidamichelson I can do this, but just a note that the data structure for the notes is different, that is why they are displaying differently. 10 has multiple notes, 1 has a single note with paragraphs.

**Comment by wlpotter** [comment]
Thanks for catching this! This looks to be working correctly when there are multiple tei:note elements. Example: https://bl.vuexistapps.us/manuscript/623#msPart5 (under item 14 of part 5).

@davidamichelson I know we do have other cases of multiple tei:p elements within the tei:note. I'll create a separate issue for working out how these should display (#188)
