### ISSUE TITLE
Missing Archive.org Link in HTML for https://bl.vuexistapps.us/manuscript/70

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#166]
@wsalesky For some reason the Archive.org link for https://bl.vuexistapps.us/manuscript/70 is not showing in the HTML

```<ref type="internet-archive-pdf" target="https://archive.org/details/catalogueofsyria03brituoft/page/1123"/>```

**Comment by davidamichelson** [comment]
[image: Screen Shot 2023-07-19 at 8.19.17 AM.png]Thanks, it should be right
at the top of the record. Here is what it looks like in MS 10

**Comment by wsalesky** [comment]
@davidamichelson This is triggered by the following element: 
t:idno[@type='Wright-BL-Roman'] 70.xml does not seem have this idno.

**Comment by wlpotter** [comment]
Odd! I'll fix this in the data and check that there are not others like it

**Comment by wlpotter** [comment]
I fixed this in record 70, not sure if webhooks will catch the change or not? (looks like they might not). I'll leave this open to confirm that it's fixed. I also made a separate data issue (@davidamichelson ) for handling the other edge cases where we might not have the BL-Roman idno
