### ISSUE TITLE
Create browse 'abstract' for manuscript records

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#169]
Using as example: https://bl.vuexistapps.us/manuscript/10

Final version:
London, BL, Add. 12178 | Wright CLXI | A.D. 899 / A. Gr. 1210
URI: [http://syriaca.org/manuscript/10](http://syriaca.org/manuscript/10)
East Syriac script | Parchment Codex | 312 ff. | Origin: The convent of Mār Gabriel (also called the convent of the Confessors) near Harrān
Contents Summary: The Book of the Collections of the Vowel-points and Readings, which are in the Holy Scriptures; A selection of passages from the Scriptures, to illustrate the use of the various signs of punctuation and accentuation, separately and in combination.; On various letters of the alphabet and their combinations; A brief explanation of certain critical marks attached to words in the biblical text; Traditions of the Masters of the Schools.

----

Xpaths:

- "London, BL, Add. 12178" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifer/idno[@type="BL-Shelfmark-display"]`
    - https://github.com/srophe/britishLibrary-data/issues/608 is a data issue for adding this display shelf mark. For testing purposes I've added it manually to https://bl.vuexistapps.us/manuscript/10
- "Wright CLXI" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifier/idno[@type="Wright-BL-Roman"]`
- "A.D. 899 / A. Gr. 1210" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/origDate` preferring first `origDate[@calendar="Gregorian"]`. There could potentially be more than two origDate elements, in which case all should be concatenated with the " / "
- "URI: [http://syriaca.org/manuscript/10](http://syriaca.org/manuscript/10)" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/idno[@type="URI"]` (with "URI: " supplied by app)
- "East Syriac script" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/handDesc/handNote[1]/@script`, based on table in [this comment](https://github.com/srophe/britishLibrary/issues/45#issuecomment-1490626040)
- "Parchment" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/@material` with value based on [this comment, no. 1](https://github.com/srophe/britishLibrary/issues/57#issue-1658832846)
- "Codex" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/@form`, but capitalizing the values
- "312 ff." = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/extent/measure/text()`
- "Origin: The convent of Mār Gabriel (also called the convent of the Confessors) near Harrān" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/origPlace` (text nodes only), "Origin: " supplied by app
- "Contents Summary: ..." = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/head/note[@type="contents-note"]`, with "Contents Summary: " supplied as label
    - Note: https://github.com/srophe/britishLibrary-data/issues/573 is a data issue for revising the contents note related to this change, but all records should have this data already

**Comment by wlpotter** [comment]
@davidamichelson I added xpaths to the above comment, but there are a few issues we should discuss before it's ready I think

**Comment by wlpotter** [comment]
One note here on composite mss. We'll probably want to include the list of parts instead/in addition to the contents summary?

**Comment by wlpotter** [comment]
@wsalesky this should be ready for implementing. These will appear for each manuscript on the browse and search results page (currently we have only the record title and URI). Let me know if I can clarify any of the above notes

**Comment by wsalesky** [comment]
Updated.

**Comment by wlpotter** [comment]
This looks good (except for the data updates I need to make which we discussed on Tuesday). I did notice one thing that's off.

The values for the material seem to be showing the attribute value rather than the label. So, for example, the first result (https://bl.vuexistapps.us/manuscript/1153) gives "chart" rather than "Paper". The xpath is right, but the value should be converted using the table listed [here, in item 1](https://github.com/srophe/britishLibrary/issues/57#issue-1658832846):

"perg" --> "Parchment"
"chart" --> "Paper"
"mixed --> "Mixed Material

**Comment by wsalesky** [comment]
fixed: https://github.com/srophe/britishLibrary/pull/245

**Comment by davidamichelson** [comment]
@wsalesky some items are missing

Example based on https://bl.vuexistapps.us/browse.html?start=50

Currently displaying:

```
CLXI | A.D. 899 / A. Gr. 1210
```

update to:
```
 London, BL, Add. 12178 | Wright CLXI | A.D. 899 / A. Gr. 1210
```

Notes:
"London, BL, Add. 12178" = `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifer/idno[@type="BL-Shelfmark-display"]`

    https://github.com/srophe/britishLibrary-data/issues/608 is a data issue for adding this display shelf mark. For testing purposes I've added it manually to https://bl.vuexistapps.us/manuscript/10

"Wright CLXI" = `Wright` + `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifier/idno[@type="Wright-BL-Roman"]`
Note: Please hard code in "Wright"

**Comment by davidamichelson** [comment]
Lastly, could you please find a way visually to help distinguish between entries? Perhaps putting the first line in bold:
 **London, BL, Add. 12178 | Wright CLXI | A.D. 899 / A. Gr. 1210**

And perhaps also a light grey line between each entry?

**Comment by wsalesky** [comment]
@davidamichelson Those paths are already in the display, can you give me record #s for the ones that are not correctly outputting?

**Comment by wlpotter** [comment]
An example from https://bl.vuexistapps.us/browse.html?start=50 is https://bl.vuexistapps.us/manuscript/1092 (the third hit on that page). It does have the altIdentifier for the "BL-Shelfmark-display" idno that isn't displaying

Note: the first two hits look to be multi-part/composite mss, so will likely need a separate issue.

**Comment by wlpotter** [comment]
This looks great, thanks!
