### ISSUE TITLE
On msContents msItems, experiment with how to display outline levels (bullets?)

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#17]

**Comment by wlpotter** [comment]
Oh wait, it looks like this one only goes to 4 levels (the xml:ids were just mislabeled...)

193 does go to 5 levels:

https://bl.vuexistapps.us/manuscript/193
XML: https://github.com/srophe/britishLibrary-data/blob/main/data/tei/193.xml

**Comment by wlpotter** [comment]
I'm going to close this one. I think we are planning to review msContents display in the coming weeks, so we will open additional issues as needed
