### ISSUE TITLE
Please add Grey header background and reduce margin at the start of the Physical Description, Manuscript Contents, and Additions boxes for multipart manuscripts

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#177]
Based on https://bl.vuexistapps.us/manuscript/1
App Version: 2.13
Data Version: 0.07

Please see images below. Perhaps this has to do with the layers/levels of boxes? Could you please add in the grey colored header background and reduce the amount of whitespace or margin at the top   of the Physical Description, Manuscript Contents, and Additions boxes for multipart manuscripts as seen in https://bl.vuexistapps.us/manuscript/1

<img width="723" alt="Screenshot 2023-07-26 at 3 35 15 PM" src="https://github.com/srophe/britishLibrary/assets/3083773/7d2f7dcb-3c01-4622-9498-e193fbc32345">

This same space is not present in single part manuscripts, see below from https://bl.vuexistapps.us/manuscript/10

<img width="492" alt="Screenshot 2023-07-26 at 3 38 35 PM" src="https://github.com/srophe/britishLibrary/assets/3083773/02218333-7b9a-491f-821e-3e3f0bbbb4e2">

**Comment by wsalesky** [comment]
@davidamichelson How does it look now?

**Comment by davidamichelson** [comment]
Looks great!
