### ISSUE TITLE
Collapse Advanced Search Box on Search Results

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#179]
When displaying search results, please show a collapsed version of search box (with ability to expand) so that the results are closer to the top of page and more prominent.

**Comment by wsalesky** [comment]
@davidamichelson Updated, close if you like the way it works.

**Comment by davidamichelson** [comment]
@wsalesky Can we save the search parameters in the box?
Also, can we rename the button from "Search Options" to "Show Search Options".
Lastly, what about putting it in the center rather than the right hand side, and moving the "Advanced Search" label to the center to: "Advanced Search (Show Search Options)"

**Comment by davidamichelson** [comment]
Any update?

**Comment by wsalesky** [comment]
Done, will push new version this afternoon.
