### ISSUE TITLE
In msParts, hand/script, material, form, and folio extent not displaying correctly

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#186]
Example record: https://bl.vuexistapps.us/manuscript/1 (see also https://bl.vuexistapps.us/manuscript/100)
Compare to https://bl.vuexistapps.us/manuscript/10

The "manuscript info" section of the msParts do not currently display the hand/script, material, form, and folio extent correctly.

The two parts of https://bl.vuexistapps.us/manuscript/1 currently have an empty line; the parts of https://bl.vuexistapps.us/manuscript/100 have:

" (multiple hands) ܀  "

Should be (using part 1 of record 100):

"Estrangela script (multiple hands) ܀ Parchment Codex, 49 leaves"

Xpaths:

- hand/script: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/handDesc/handNote/@script`
    - "(multiple hands)" included if the count of `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/handDesc/handNote` is more than one
- material: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/objectDesc/supportDesc/@material`
- form: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/objectDesc/@form`
- `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/objectDesc/supportDesc/extent/measure/@quantity` + label of "leaves" (or "leaf" if only 1)

This is app version 2.14

**Comment by wsalesky** [comment]
Fixed: https://github.com/srophe/britishLibrary/pull/191
