### ISSUE TITLE
In multi-part table of contents, add "CE" as label to date range

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#187]
Example: https://bl.vuexistapps.us/manuscript/1

For the tables of contents in multi-part manuscript records, we include the date range. We'd like to add a label to make clear that these are dates:

current:

"1. Add. 12,133, foll. 1–108 (700 - 750)"

new:

"1. Add. 12,133, foll. 1–108 (700 - 750 CE)"

**Comment by wsalesky** [comment]
@wlpotter I do not see 'CE' in the XML date. Am I missing it, or are we hardcoding it?

**Comment by wlpotter** [comment]
Sorry for the confusion. We are hard coding the "CE" label

**Comment by wsalesky** [comment]
Fixed: https://github.com/srophe/britishLibrary/pull/192

**Comment by davidamichelson** [comment]
Hi @wsalesky We love this but realize we have an edit. This "CE" is hard coded in, but it should only appear if there is attribute values in origDate. If there are not values please don't display the parentheses or CE. See an example of how these are displaying but empty here in parts 6-7: https://bl.vuexistapps.us/manuscript/720

**Comment by wsalesky** [comment]
Updated
