### ISSUE TITLE
In msParts, manuscript URI is not displaying

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#189]
Similar to #186. Example record: https://bl.vuexistapps.us/manuscript/100

Currently, in the msPart sections there is a blank line here (right above the line that begins, "Description based on Wright..."

This line should contain the URI for that part, e.g.:

"URI: http://syriaca.org/manuscript/101"

Xpath: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/msIdentifier/idno[@type="URI"]`

**Comment by wsalesky** [comment]
Fixed: https://github.com/srophe/britishLibrary/pull/190
