### ISSUE TITLE
Script and Material Facets for Browse and Search

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#198]
@wsalesky Could you please add these as facets for browse and search results:

Script: results facet 
Material: results facet 

Here are those xpaths:
    Script: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/handDesc/handNote/@script. We would want to use the labels from https://github.com/srophe/britishLibrary/issues/62#issue-1658870275.
    Material: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/@material. We would want the labels from https://github.com/srophe/britishLibrary/issues/57#issue-1658832846 under "Material Support"

**Comment by wsalesky** [comment]
Fixed

**Comment by wlpotter** [comment]
Here are Xpaths for the msParts:

- Script: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/handDesc/handNote/@script`
- Material: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/objectDesc/supportDesc/@material`

The labels should be the same as what's linked [above](https://github.com/srophe/britishLibrary/issues/198#issue-1860033281)

**Comment by wsalesky** [comment]
Please check the updates.

**Comment by wlpotter** [comment]
These look to be working to me
