### ISSUE TITLE
Place Advanced search not excluding some results

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#201]
For "Place" Advanced search, please change the path slightly. Search inside any placeName EXCEPT when placeName is a direct child of persName. Please exclude results from persName/placeName from results.

Example:
Right now this search: https://bl.vuexistapps.us/search.html?keyword=&author=&title=&syrText=&syrRubricsLimit=true&syrFinalRubricsLimit=true&syrIncipitsLimit=true&syrExplicitsLimit=true&syrColophonsLimit=true&syrOtherLimit=true&place=Edessa&person=&locus=

returns this record: [http://syriaca.org/manuscript/85](https://bl.vuexistapps.us/manuscript/85) but should not

```
<persName ref="http://syriaca.org/person/42">
Jacob of
<placeName ref="http://syriaca.org/place/45">Batnae</placeName>
</persName>
```

**Comment by wsalesky** [comment]
Fixed: https://github.com/srophe/britishLibrary/pull/208
