### ISSUE TITLE
Advanced Search boxes need right justification when window is maximized

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#203]
Please see picture. When the window size is maximized two search boxes (for place and person) appear shorter than the others:

<img width="2526" alt="Screenshot 2023-08-21 at 3 02 33 PM" src="https://github.com/srophe/britishLibrary/assets/3083773/dc5e3252-3bcd-41fe-be4a-3136d0b65bf8">

**Comment by wsalesky** [comment]
Fixed: https://github.com/srophe/britishLibrary/pull/206
