### ISSUE TITLE
On Multipart MSS change the font size and color for rendering the shelfmark 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#204]
Please see the image below. One multipart manuscripts, could you please make the shelfmarks found here:

msPart/msIdentifier/altIdentifier/idno @type="BL-Shelfmark"

display with the same larger size (and perhaps the same color if it doesn't look bad on the grey backround) as: titleStmt/title()

If using the blue looks odd please change both to black.
![Shelfmark](https://github.com/srophe/britishLibrary/assets/3083773/c4349e3f-48c5-4c4b-95d9-bc8ca193e02b)

**Comment by wsalesky** [comment]
Fixed. https://github.com/srophe/britishLibrary/pull/205
