### ISSUE TITLE
Display of Greek text in child elements of `//msItem/note/p`

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#219]
Split off from #188. In child elements of `//msItem/note/p`, Greek text is not displaying properly even when tagged with `@xml:lang="grc"`. Example record: https://bl.vuexistapps.us/manuscript/30

Example data:

```
<reg xml:lang="grc">συντακτήριος</reg>
```
(in `//msItem/note/p/choice/reg`)

Note that the Syriac that is not currently displaying properly is likely because its element (tei:orig) is not tagged with an xml:lang, for which I've created a data issue

**Comment by wsalesky** [comment]
@wsalesky Note to self: This is a problem I made for myself by using em rather than px for fonts all through the app, so nested fonts are basing size on the parent font, not a absolute font. Will need to rework the whole CSS to fix. This will apply to all apps. 

FYI @wlpotter @davidamichelson

**Comment by davidamichelson** [comment]
Thanks! And for the record, it was about time you made a problem rather
than just fixing ours. We are happy to pay for the fix so be sure to bill
us!

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter How does this look?

**Comment by wlpotter** [comment]
I'm still getting the same issue for the Greek:

![Screenshot from 2023-09-29 09-04-17](https://github.com/srophe/britishLibrary/assets/44096602/b94a7452-7e49-4051-9c60-39c4d2167535)

App version 2.24

**Comment by wsalesky** [comment]
@wlpotter how about now?

**Comment by wlpotter** [comment]
Yes, this looks to be working now -- thanks!
