### ISSUE TITLE
About this manuscript script information for mss with a "sole" handNote

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#222]
In the original request for the script info to be included in the about this manuscript box (cf. #40 ), we gave too specific of an xpath. Example record: https://bl.vuexistapps.us/manuscript/752

Currently the App looks for `handNote[@scope="major"]`, but we'd like this to also look for `handNote[@scope="sole"]`.

Full Xpath: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/handDesc/handNote`
- for multi-part this becomes: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/handDesc/handNote`

**Comment by wsalesky** [comment]
Fixed
