### ISSUE TITLE
Indexing for Facets

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#223]
@wsalesky At present the facets (take for example "Material) appear to only be returning results for manuscripts that do NOT have any child msParts.

What information do you need from us to make the XML files with msParts also appear in facets? I think we only gave you one path and needed to give you two.

Related to issues #88 #84

**Comment by wlpotter** [comment]
I added xpaths for subject and date to the corresponding issues (linked above). I also reopened #198 and added xpaths there

**Comment by wsalesky** [comment]
Please check the updates.

**Comment by wsalesky** [comment]
@wlpotter How do these look now?

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson the updated facets pick up a lot of funky stuff in the data in the script facet.

**Comment by wlpotter** [comment]
Oh right, I forgot that the list of language codes and labels we gave for the facet were only pulling from the records without msParts...I will make a separate issue for me to send the updated lists of language codes
