### ISSUE TITLE
Multiple Facets

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#228]
On the facets, where a MSS has more than one language, does it show up multiple times in the browse?  For example “Greek” manuscripts also have "Syriac" so when one clicks on the 4 greek, other languages should still show
https://bl.vuexistapps.us/browse.html?&startDate=0139-12-01&endDate=1901-08-30&all-classfication=on&all-script=on

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter This is partially fixed. You can now select multiple facets. however the lucene facets default to OR, not AND, which gives us some odd results. I will open a new issue for this.
