### ISSUE TITLE
Multiple facets default is OR not AND

### ISSUE THREAD

**Issue by wsalesky** [srophe/britishLibrary#232]
This is built in Lucene functionality. I will need to come up with some hack around it. Still thinking of the best way to do it.

**Comment by wsalesky** [comment]
Investigating with eXist-db list.

**Comment by davidamichelson** [comment]
Any update?

**Comment by wsalesky** [comment]
Still a work in progress

**Comment by wsalesky** [comment]
@davidamichelson  @wlpotter  Added to the site. Please check and let me know what you think. Let me know in particular if the queries seem slower.

**Comment by wsalesky** [comment]
Fixed
