### ISSUE TITLE
Compile full list of used langauge codes

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#240]
Cf. #223. The language codes we initially provided for facets was incomplete as it only gave the language codes found in manuscripts without msParts. I'll add the full list below

**Comment by wlpotter** [comment]
@davidamichelson we should confirm this list is correct, but here is what I've found looking at all of the `//handNote/@script` values, and their corresponding labels:

- ar | Unspecified Arabic script
- ar-Syrc | Arabic Garshuni script
- cop | Coptic
- grc | Greek
- he | Hebrew
- hy | Armenian
- la | Latin
- syr | Unspecified Syriac script
- syr-Syre | Estrangela script
- syr-Syrj | West Syriac script
- syr-Syrn | East Syriac script
- syr-x-syrm | Melkite Syriac script
- syr-x-syrp | ???


----
A few notes/questions:

- We also have one case of "xcl" for "Classical Armenian" that I'd be in favor of updating to "hy" as it is just "a word written in Armenian capitals" (addition 1 in https://bl.vuexistapps.us/manuscript/265)
- Do we need "Unspecified x script" for all of the languages?
- For syr-x-syrp this could either be "Palestinian Syriac", Wright's term for it, or "Christian Palestinian Aramaic". Though the latter is both a script and language designation, i.e. it is a separate dialect of Aramaic.
    - the one case is the undertext of 14,718 (https://bl.vuexistapps.us/manuscript/598#msPart2), so likely CPA language and script. This is the Glottolog URI: https://glottolog.org/resource/languoid/id/chri1239

**Comment by davidamichelson** [comment]
qhy-x-cpa | Christian Palestinian Aramaic

**Comment by wlpotter** [comment]
Note to self: update data to change syr-x-syrp to qhy-x-cpas

**Comment by wlpotter** [comment]
Closing this; the language codes and labels are now all in the langUsage element in every file, which is used in the schema
