### ISSUE TITLE
Change to Table of Contents for Multi-Part MS

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#254]
This is a spin off of https://github.com/srophe/britishLibrary/issues/156

Could you please try out this change to see if we like it better? (It may look too cluttered).

Right now the table of contents looks like this https://bl.vuexistapps.us/manuscript/720):
```
London, BL, Add. 11739
URI: http://syriaca.org/manuscript/720

    1. Add. 14,739, foll. 1–6. (1100 - 1200 CE)
    2. Add. 14,739, foll. 7–11 (1000 - 1200 CE)
    3. Add. 14,739, foll. 12–14 (1100 - 1200 CE)
    4. Add. 14,739, foll. 15–18 (1200 - 1300 CE)
    5. Add. 11,739, foll. 19–22 (1200 - 1400 CE)
    6. Add. 14,739, fol. 23 ( - CE)
    7. Add. 14,739, fol. 24 ( - CE)
```
We would like to see how it would look with the URIS for the parts displayed as well:
```
London, BL, Add. 11739
URI: http://syriaca.org/manuscript/720

    1. Add. 14,739, foll. 1–6. (1100 - 1200 CE) [http://syriaca.org/manuscript/721]
    2. Add. 14,739, foll. 7–11 (1000 - 1200 CE) [http://syriaca.org/manuscript/722]
 ```
etc.

The path would be

`msPart/msIdentifier/idno type="URI"`

**Comment by wsalesky** [comment]
Added: https://github.com/srophe/britishLibrary/pull/257

**Comment by wsalesky** [comment]
@davidamichelson Do we like this? Should I close it?

**Comment by wlpotter** [comment]
This looks good!
