### ISSUE TITLE
Display issues with "Defective" (`//msItem[@defective="true"]` label

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#255]
There are two, possibly related (?), issues with how 'defective' manuscript items are labelled. Example: contents item 1 in https://bl.vuexistapps.us/manuscript/152.

This should apply to all `//msItem[@defective="true"]`

First, in the child title (`/msItem/title`), this should display "[defective]" after the title's text node:

Current: "Item 1 (Fol. 1): The four Gospels, according to the Harklensian version"
New: "Item 1 (Fol. 1): The four Gospels, according to the Harklensian version [defective]"

Second, it appears we may have had this styling previously as it _is_ getting applied to `//msItem[@defective="true"]/note/title`. For example, in the note to this item: "The Ammonian sections and Eusebian canons [defective]". We do not want it to appear in these titles, just restricted to the immediate child title of the defective msItem.

**Comment by wlpotter** [comment]
Reopening as I spotted another XPath I hadn't included here: `//msItem[@defective="true"]/note/p/title`. I believe we can just have it not display "Defective" label on any descendant tei:title elements of a tei:note (i.e., `//msItem[@defective="true"]/note//title`

**Comment by wlpotter** [comment]
The second note in item 1 of https://bl.vuexistapps.us/manuscript/638 is an example:

>The principal authorities cited in this work are—
>
>Athanasius: on the Psalms [defective], foll. 28 a, 78 a and b; ܏ܡܐ ܕܥܠ ܡܬܒܪܢܫܢܘܬܗ ܕܡܠܬܐ [defective], fol. 30 a.

**Comment by wsalesky** [comment]
Fixed here: 
https://github.com/srophe/britishLibrary/pull/278
