### ISSUE TITLE
Multiple tei:rubric elements in tei:msItem should display on their own line

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#276]
Item 19 in https://bl.vuexistapps.us/manuscript/45 is an example:

>Title:ܕܩܕܝܫܐ ܡܪܝ ܐܝܘܐܢܢܝܣ ܡܐܡܪܐ̣. ܕܥܠ ܨܘܡܐ ܩܕܝܫܐ ܕܐܪܒܥܝܢ  Title:ܕܐܪܒܥܐ ܒܫܒܐ ܕܫܒܬܐ ܩܕܡܝܬܐ ܕܨܘܡܐ

Each tei:rubric should appear on its own line, and both can have the label "Title", e.g.:

>Title: ܕܩܕܝܫܐ ܡܪܝ ܐܝܘܐܢܢܝܣ ܡܐܡܪܐ̣. ܕܥܠ ܨܘܡܐ ܩܕܝܫܐ ܕܐܪܒܥܝܢ
>Title: ܕܐܪܒܥܐ ܒܫܒܐ ܕܫܒܬܐ ܩܕܡܝܬܐ ܕܨܘܡܐ

I am also noticing that there might be a space missing between the colon of the "Title" label and the Syriac, though this may be a bidi display issue?

**Comment by wsalesky** [comment]
Fixed
