### ISSUE TITLE
Syriac display font selection not working for all choices

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#283]
Example record: https://bl.vuexistapps.us/manuscript/50

- Serto selection (Serto Antioch) appears to still be an Estrangela font?
- sizing of the fonts seems to vary between Estrangela Talada, East Syriac Adiabene, and Serto Antioch

**Comment by wsalesky** [comment]
How does it looks now? https://github.com/srophe/britishLibrary/pull/285

**Comment by wlpotter** [comment]
I'm still getting the same issue with Serto (Serto Antioch), looking at https://bl.vuexistapps.us/manuscript/50 (app version 2.34)

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson @dlschwartz 
These are the fonts I am using (the first 3): https://github.com/srophe/britishLibrary/tree/main/resources/fonts

I do not see any issue in the CSS that calls the font, so perhaps there is an issue with the actual font file? Can one of you take a look and let me know? These are the ones I downloaded from beth mardutho, but if there is a different set I should be using, let me know.

**Comment by wlpotter** [comment]
@wsalesky Ah, it looks like there are two fonts named Antioch...the one that is downloaded with the main bundle from Beth Mardutho is Estrangelo Antioch.

Instead, we want to use the Serto Antioch bible font (https://bethmardutho.org/resources/syriacpc/), a direct download of the .zip file is here: https://bethmardutho.org/wp-content/uploads/2020/12/SertoAntochBible_2020_Release-4.zip

**Comment by wsalesky** [comment]
That explains it! I will get that up today, thanks for looking!

**Comment by wlpotter** [comment]
For reference, a low-res image of the font is availble on the "Sample page", here: https://www.gorgiaspress.com/syriac-english-new-testament (about 75% down the page)

**Comment by wsalesky** [comment]
@wlpotter does this look correct? 
<img width="402" alt="Screenshot 2024-02-20 at 2 07 44 PM" src="https://github.com/srophe/britishLibrary/assets/1168206/9d64cf71-52e2-45cc-a584-12d677369271">

**Comment by wsalesky** [comment]
Fixed! You may need a hard refresh to see the updated font.
