### ISSUE TITLE
Restrict keyword searching to `//msDesc`

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#296]
@wsalesky I noticed that basic keyword searching is returning results from everywhere in the document, e.g. https://bl.syriac.uk/search.html?keyword=decoration with results from `//titleStmt/respStmt/resp` and `//revisionDesc/change`.

Could we limit/restrict basic keyword searches to look just in `/TEI/teiHeader/fileDesc/sourceDesc/msDesc`?

**Comment by wsalesky** [comment]
@wlpotter Can you add a few test searches and what they should be returning?

**Comment by wlpotter** [comment]
Yes, here is an example search:

https://bl.syriac.uk/search.html?keyword=created that has 577 hits because it is finding "created" in `/TEI/teiHeader/revisionDesc/change`. Doing a search in oXygen but restricting it to search only in `//msDesc` gives just 5 results.

Similarly, the search for "decoration" (https://bl.syriac.uk/search.html?keyword=decoration) gives 72 keyword matches; but should be only 22 hits (across 13 records).

Let me know if this helps or if I should provide more detail
