### ISSUE TITLE
Update app to handle new record URI pattern

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#297]
@wsalesky I have just updated the data to use the new URI pattern.

Old: http://syriaca.org/manuscript/
New: https://bl.syriac.uk/ms/

For example: https://bl.syriac.uk/ms/142 (previous URI: http://syriaca.org/manuscript/142; currently-resolving URL: https://bl.syriac.uk/manuscript/142)

Could you update the app and push a new build to use the new URI base pattern?

**Comment by wsalesky** [comment]
The new data is up

**Comment by wsalesky** [comment]
@wlpotter Can this be closed?

**Comment by wlpotter** [comment]
Yes, the new data is up and looks good thanks!
