### ISSUE TITLE
Update labels for script codes

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#310]
Split off from #240

The following table of language codes should be used for both the about this manuscript box and in the hand note section (cf. #62 for a previous change to these labels).

The data come from the attribute values, here: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/handDesc/handNote/@script` (or here for multi-part mss: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/handDesc/handNote/@script`

ar | Unspecified Arabic script
ar-Syrc | Arabic Garshuni script
cop | Unspecified Coptic script
fr | Unspecified French script
grc | Unspecified Greek script
he | Unspecified Hebrew script
hy | Unspecified Armenian script
la | Unspecified Latin script
syr | Unspecified Syriac script
syr-Syre | Estrangela script
syr-Syrj | West Syriac script
syr-Syrn | East Syriac script
syr-x-syrm | Melkite Syriac script
qhy-x-cpas | Christian Palestinian Aramaic script
mixed | Mixed scripts

An example of a record not currently working: https://bl.syriac.uk/ms/1423#msPart2.

Info box current: "܀  Leaf, 1 leaf." ; updated: "Unspecified Coptic script ܀  Leaf, 1 leaf."
Hand note current: "Hand 1 (sole, ):" ; updated: "Hand 1 (sole, Unspecified Coptic script):"

**Comment by davidamichelson** [comment]
Related to https://github.com/srophe/britishLibrary-data/issues/1542

**Comment by wsalesky** [comment]
Fixed
