### ISSUE TITLE
Remove trailing whitespace after decoration typing

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#311]
Example record: https://bl.vuexistapps.us/ms/427. There is an extra space added after the decoration typing; data from 

Data found in `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/decoDesc/decoNote/@type` (or `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/physDesc/decoDesc/decoNote/@type` for multi-part)

Current: "Decoration (Ornamentation ):"
Updated: "Decoration (Ornamentation):"

XML:
```
<decoNote xml:id="decoNote1" type="ornamentation">
```

**Comment by davidamichelson** [comment]
@wsalesky Just a ping to remind you of this.

**Comment by wsalesky** [comment]
Done: https://github.com/srophe/britishLibrary/pull/322
