### ISSUE TITLE
Add a pop up message to bibl[ptr]/citedRange/@unit="entry"

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#316]
@wsalesky When we have bibl[ptr]/citedRange/@unit="entry" please make the text node value of citedRange look like a live URL (blue or whatever) and when clicked on have a pop up message display that says: "This entry number is from Wright's printed catalogue. Due to renumbering, Wright's entry numbers do not match the numbering used in this digital catalogue."

**Comment by wsalesky** [comment]
@davidamichelson what should the popup say?

**Comment by davidamichelson** [comment]
Sorry, here you go!

**Comment by davidamichelson** [comment]
@wsalesky Sorry I changed it again

**Comment by wsalesky** [comment]
Fixed
