### ISSUE TITLE
New Feature: Add Link to Github File on Record Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#319]
@wsalesky  

We would like to add another button on the record page next to the print, TEI/XMl, RDF, etc. buttons.
![Screenshot 2024-05-22 at 11 26 29 AM](https://github.com/srophe/britishLibrary/assets/3083773/28dcea11-0f86-42d4-92ad-8acbbacb9bf6)

This button would link to the version of the file as found on the "main" branch in the data repository on github.

For example for https://bl.syriac.uk/ms/10 the link would point to https://github.com/srophe/britishLibrary-data/blob/main/data/tei/10.xml (this link could be constructed from https://github.com/srophe/britishLibrary-data/blob/main/data/tei/ +URI number +file extension)

Please use a small github logo for the button (no need for text).

Please let me know if this makes sense.

For right now, just implement this on bl.syriac.uk but we would likely want to port this to the Srophe app in general and use it on Syriaca.org for example.

**Comment by davidamichelson** [comment]
Yes

**Comment by wsalesky** [comment]
Added here: https://github.com/srophe/britishLibrary/pull/323
