### ISSUE TITLE
Changes to "This manuscript contains 1 items . N.B. Items were re-numbered by Syriaca.org and may not reflect previous numeration."

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#320]
@wsalesky could you please edit this message which is generate for each record?

- [x] Please remove the white space before the period in ```This manuscript contains 1 items .``` so that it reads ```This manuscript contains 1 item(s).```
- [x] Please change the wording ```N.B. Items were re-numbered by Syriaca.org and may not reflect previous numeration.``` to ```N.B. Items were re-numbered for this online catalog and may not reflect William Wright's previous numeration.```

Thanks!

**Comment by wlpotter** [comment]
It looks like this only occurs in multi-part mss? Compare https://bl.syriac.uk/ms/312, which has "Note: Item numbering updated in digital edition." with the parts in https://bl.syriac.uk/ms/1 which have "This manuscript contains 1 items . N.B. Items were re-numbered by Syriaca.org and may not reflect previous numeration."

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/britishLibrary/pull/327
