### ISSUE TITLE
Updates to display for authors and editors of msItems

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#336]
@wsalesky We updated how author elements are encoded, which seems to be causing an extra whitespace to appear.

Author names are now in `//msItem/author/persName` rather than directly as text nodes of `//msItem/author`. This should also apply to `//msItem/editor/persName` elements

Example from https://bl.syriac.uk/ms/293 with an extra space, "Chrysostom .":

Current:

>Item 1 (Fol. 1a): John Chrysostom . The Commentary...

Requested change:

>Item 1 (Fol. 1a): John Chrysostom. The Commentary...

XML:

```
<author ref="http://syriaca.org/person/573">
  <persName xml:lang="en">John Chrysostom</persName>
</author>
<title>The Commentary...</title>
```

**Comment by wlpotter** [comment]
Also, with this change we may have multiple `//author/persName` elements, e.g.

```
<author>
  <persName xml:lang="en">John Chrysostom</persName>
  <persName xml:lang="syr">ܝܘܚܢܢ</persName>
  <persName xml:lang="en">John</persName>
</author>
```

We would like the first name variant (`//author/persName[1]`) to display as it currently does:

>Item 1 (Fol. 1a): John Chrysostom. The Commentary...

But we would like to add beneath a line like the following with a serial list of the remaining names (`//author/persName[position() > 1]`):

>Author Name Variants: ܝܘܚܢܢ, John

Each name should include an xml:lang attribute to help with bi-directional text display.

For editors, the label should instead be from the `editor/@role` value

**Comment by wlpotter** [comment]
Also, as you noted in [this comment](https://github.com/srophe/britishLibrary/issues/340#issuecomment-2152069159), there may be multiple authors or editors. In such cases, the way they currently display (separated by commas), should be fine, though we would only be displaying `author/persName[1]` in-line with the title as it does currently.

Example of multiple author record: https://bl.syriac.uk/ms/1019

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/britishLibrary/pull/350
