### ISSUE TITLE
Render `bibl/ptr/@target` and `bibl/ref/@target` as hyperlinks

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#339]
@wsalesky In some cases we have tei:bibl elements with either `ref/@target` or `ptr/@target`. We would like to use these attribute values to create a hyperlink.

Example from https://bl.syriac.uk/ms/1078 item 18:

>Note: See Add. 14,575, no. 5.

Should become

>Note: See [Add. 14,575, no. 5](https://bl.syriac.uk/ms/311).

XML:

```
<note>See 
  <bibl>Add. 14,575<ptr target="https://bl.syriac.uk/ms/311"/>, <citedRange unit="entry">no. 5</citedRange> </bibl>.</note>
```

The link should go around the entire parent bibl element.

**Comment by wsalesky** [comment]
@wlpotter is this for all bibl elements or just bibl elements that are the child of a note element?

**Comment by wlpotter** [comment]
This should be the case for bibls in the following contexts:

- handNote
- note
- p
- decoNote

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/britishLibrary/pull/380
