### ISSUE TITLE
Displaying multiple msItem title elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#340]
We have some cases of more than one `msItem/title`, for example item 8 in Part 1 of https://bl.syriac.uk/ms/614#msPart1.

Current:

>Item 8 (Fol. 20a): Severus. On the NativityHom. epithron. xxxvi.

XML:
```
<title xml:lang="en">On the Nativity</title>
<title xml:lang="la">Hom. epithron. xxxvi.</title>
```

For `msItem/title[1]`, this would display as it currently does:

>Item 8 (Fol. 20a): Severus. On the Nativity

Each additional title (`msItem/title[position() > 1]` would appear as its own line with the label "Title":

>Title: Hom. epithron. xxxvi.

These lines would appear below the additional author names, if any (requested in #336)

**Comment by wsalesky** [comment]
@wlpotter are there ever multiple authors? Or just titles?

**Comment by wsalesky** [comment]
Done
