### ISSUE TITLE
Note elements in descendant msItems are displaying in the top-level msItem

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#343]
@wsalesky ~~I wonder if this is related to a change for #341~~ (nevermind), but appears that all the descendant tei:note elements are displaying at the top-level msItem.

Example record: https://bl.syriac.uk/ms/763

The top-level item (`msContents/msItem[1]`) only has the first two notes; the rest seem to be coming from `msContents/msItem//msItem/note`. As far as I can tell the XML data is correct -- though let me know if there is a mistake that I'm not seeing

**Comment by wsalesky** [comment]
@wlpotter opps, yes that is my fault, I will need to find a better way to get the correct notes to display.

**Comment by wsalesky** [comment]
Fixed.
