### ISSUE TITLE
Updated xpath for displaying the volume and page number of each entry

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#344]
@wsalesky during some normalizations, it looks like we changed the xpath to Wright's volume and page number.

This should now be `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/additional/listBibl/bibl/citedRange[@unit="p"]` or, for multi-part `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPartadditional/listBibl/bibl/citedRange[@unit="p"]`

(previously the citedRange `@unit` was "pp")

This is dispayed in the header/info box between the entry number and the Archive.org icon

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/britishLibrary/pull/348
