### ISSUE TITLE
Link to GitHub file in the HTML pages does not work for multi-part manuscripts

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#347]
The GitHub file link appears to be constructed based on the URL I input into my search bar. For example, although https://bl.syriac.uk/ms/2 resolves to https://bl.syriac.uk/ms/1 (since 2 is a part of 1), the GitHub link is https://github.com/srophe/britishLibrary-data/blob/main/data/tei/2.xml (this file doesn't exist because it is contained in 1.xml). Would it be possible for the GitHub link to be constructed with the ID of the containing file, even if I put in a part URI?

For reference, this was initially requested in #319

**Comment by wsalesky** [comment]
Fixed here: https://github.com/srophe/britishLibrary/pull/349
