### ISSUE TITLE
Search box for Shelfmark in Advanced Search

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#376]
Could we add a search box in the [Advanced Search](https://bl.syriac.uk/search.html) page that lets users search by the manuscript shelf mark?

The label would be "Shelfmark".

Xpaths to search in:

- `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifier/idno[@type="BL-Shelfmark"]`
- `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier/altIdentifier/idno[@type="BL-Shelfmark-simplified"]`

These could also appear in msParts:

- `/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/msIdentifier/altIdentifier/idno[@type="BL-Shelfmark"]`
- `/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/msIdentifier/altIdentifier/idno[@type="BL-Shelfmark-simplified"]`

**Comment by wlpotter** [comment]
I think we'd want wild card capabilities so someone could search, e.g. "14,1*"

**Comment by wsalesky** [comment]
@wlpotter this has been added. You will need to merge this:
https://github.com/srophe/britishLibrary-data/pull/1907

into data before it will work. Once I see that pull request merged I will rebuild the docker image and get the new search online.

**Comment by wlpotter** [comment]
Thanks! Just merged it in

**Comment by wsalesky** [comment]
@wlpotter please test and close if it works as expected

**Comment by wlpotter** [comment]
This looks like it's working!
