### ISSUE TITLE
Advanced Search options for searching decorations

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#377]
We would like to add an option to search decorations to the Advanced Search page, as well as to provide a facet for narrowing results based on decoration type.

First, the search box:

Label can be "Decorations".

Xpath to search in: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/decoDesc/decoNote`, could also be in msPart: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/physDesc/decoDesc/decoNote`

Example search "four lines of interlaced" should return record https://bl.syriac.uk/ms/10

----

Facet for narrowing results:

label can be "Decoration Type"

Xpath with data values: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/decoDesc/decoNote/@type`, could also be in msPart: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/physDesc/decoDesc/decoNote/@type`

This can function like the existing facets for material and script

**Comment by wlpotter** [comment]
Oh wait, I forgot one additional feature. Next to the search box, could we also have a drop down that lets users select a decoration type to limit results by? This would use the same data values (`decoNote/@type`), essentially just another way to select the facets.

I think it would function similarly to the place type selector in the Gazetteer: https://syriaca.org/geo/search.html

**Comment by wsalesky** [comment]
@wlpotter this has been added. You will need to merge this: 
https://github.com/srophe/britishLibrary-data/pull/1907

into data before it will work. Once I see that pull request merged I will rebuild the docker image and get the new search online.

**Comment by wsalesky** [comment]
@wlpotter Added. Once the index file is updated for the data I can run a new build on the server.

**Comment by wlpotter** [comment]
Thanks @wsalesky ! I just pulled in the decoNote index change

**Comment by wsalesky** [comment]
@wlpotter please test and then close if it works as expected.

**Comment by wlpotter** [comment]
Yes, this looks to work as expected
