### ISSUE TITLE
Add an about this manuscript box

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#40]
See comment below for the mockup with xpaths

**Comment by davidamichelson** [comment]
The mock up for this box with xpaths is here: https://docs.google.com/document/d/1wXhlqdGbqurhWCSdzGp74NIoXbflFhrrGcHjQdqMmKM/edit?usp=sharing

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson I'm still waiting on a few xpaths for this issue, please see google doc.

**Comment by wlpotter** [comment]
Sorry about that! I added the last xpaths (I think they're all in now, but let me know if I'm still missing some). Thanks much!
