### ISSUE TITLE
Visualization Change: Remove "Current location" and "Identification" sections.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#41]
Please suppress these sections, this information will appear elsewhere.

**Comment by davidamichelson** [comment]
Please also remove the URI line (this will be added in the new about box)
![Screen Shot 2023-03-22 at 10 28 59 AM](https://user-images.githubusercontent.com/3083773/226954913-1607d061-213a-43c6-bcac-c9564ae00702.png)

**Comment by wsalesky** [comment]
Done
