### ISSUE TITLE
Changes to //physDesc/decoDesc display

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#44]
Please change label to be without numbers. Eg. "Decoration:" Not "Decoration 1:"

**Comment by wsalesky** [comment]
@davidamichelson In my example record the <locus> element has text, should that be included, or should it be entirely constructed via xslt? 

For example: what would you like the following to look like: 

```
<decoNote xml:id="decoNote1" type="illustration">
  <desc>
    On fol.
    <locus from="57a">57 a</locus>
    , there are two rudely drawn figures, representing the Annunciation of the Virgin; and on fol.
    <locus from="114b">114 b</locus>
    , a head.
  </desc>
</decoNote>
<decoNote xml:id="decoNote2" type="ornamentation">
  <desc>
  There are also coloured ornaments in various patterns at the end of several lessons; e.g. foll.
  <locus from="4a">4 a</locus>
  ,
  <locus from="6b">6 b</locus>
  ,
  <locus from="13b">13 b</locus>
  ,
  <locus from="15b">15 b</locus>
  ,
  <locus from="57b">57 b</locus>
  .
  </desc>
</decoNote>
```

**Comment by davidamichelson** [comment]
Good catch. Please add this logic:

IF desc/locus has a textnode then don't construct the additional folio number at the end. Just display the textnode(s) of locus where they occure.

For any cases where desc has child locus but locus does not have a textnode and does have attribute values, please construct with XSLT.

For any cases where desc has preceeding sibling locus and does not have child element locus, then construct with XSTL as above.
