### ISSUE TITLE
//physDesc/handDesc

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#45]
Please change the HTML rendering in the following ways to suppress the scope label and the medium label and abbreviate the script label).

Current (based on https://bl.vuexistapps.us/manuscript/10)

Hand 1:
Scope:major
Script: Vocalized East Syriac
Medium: unknown
The manuscript is written in a small, Nestorian character, and dated A. Gr. 1210, A.D. 899.
Hand 2:
Scope:minor
Script: Unvocalized Syriac of any variety or period
Medium: unknown
The vowels are added throughout, in the form of small dots or points, as well as various diacritical marks and signs of punctuation.
Hand 3:
Scope:minor
Script: Unvocalized Syriac of any variety or period
Medium: unknown
See additions.

Revised:

Hand 1 (major, East Syriac script): The manuscript is written in a small, Nestorian character, and dated A. Gr. 1210, A.D. 899.
Hand 2 (minor, Unspecified Syriac script): The vowels are added throughout, in the form of small dots or points, as well as various diacritical marks and signs of punctuation.

**Comment by davidamichelson** [comment]
Note on how to render the script codes. Please use this same list as found in issue #40 

"syr"= Unspecified Syriac script
"syr-Syre"= Estrangela script
"syr-Syrj”= West Syriac script
"syr-Syrn”= East Syriac script
"syr-x-syrm”= Melkite Syriac script
"grc”= Greek
"ar-Syrc”= Arabic Garshuni script
“ar” = Unspecified Arabic script

**Comment by davidamichelson** [comment]
Special note: note that in the revised version Hand 3 disappears.  Please include a logic that for any TEI:handNote where scope="minor" and the TEI:handNote/desc() contains only the string "See additions" or where the TEI:handNote/desc() textnode is empty then suppress this handNote and don't visualize it.

**Comment by davidamichelson** [comment]
@wlpotter any comments?

**Comment by wlpotter** [comment]
This looks good to me. Were we going to update the data for the last note about "See additions"?

**Comment by wsalesky** [comment]
done
