### ISSUE TITLE
Changes to //physDesc/additions display

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#46]
Please move //physDesc/additions to its own box (labelled "Additions") that occurs after the Manuscript Contents box.

**Comment by davidamichelson** [comment]
@wlpotter Any comments?

**Comment by wlpotter** [comment]
The only other change might be to have the text in the `//item/label` displayed in bold or with parentheses. E.g., in https://bl.vuexistapps.us/manuscript/10 for additional item 4:

Current:
>4 Colophon On foll. 310 b and 311 a we find a series of notes, written by the same hand as the rest of the book. The first three inform us that this books was written by Babai the deacon...

Revised:
>4 **[Colophon]:** On foll. 310 b and 311 a we find a series of notes, written by the same hand as the rest of the book. The first three inform us that this books was written by Babai the deacon...

**Comment by davidamichelson** [comment]
Okay please do make these changes as well @wsalesky

**Comment by wlpotter** [comment]
This all looks great! Just noticed that the additions are still displaying above the contents box. Would it be possible to move them down below? So that we have:

- Physical Description
- Manuscript Contents
- **Additions**

I also just noticed that there are two labels for "Additions", one in the box's border and the other within the box. Could we remove the second of these (see attached screenshot)?

![Screenshot from 2023-03-31 09-18-58](https://user-images.githubusercontent.com/44096602/229146345-474f05d8-d44e-4caa-8648-1c68e2388d37.png)

**Comment by wsalesky** [comment]
@wlpotter how does it look now?

**Comment by wlpotter** [comment]
I'm not seeing a change? The app version I'm seeing on the banner is 2.02 is that the right version?

**Comment by wsalesky** [comment]
No, it should be at 2.03, I will check the webhook.

**Comment by wsalesky** [comment]
how about now?

**Comment by wlpotter** [comment]
Yes, I see the change now -- and it looks great! Thanks!!

**Comment by wlpotter** [comment]
One last change here. Could we suppress the additions box if there are no `//additions/list/item` elements? It looks like it is still there when empty, e.g. https://bl.vuexistapps.us/manuscript/142

**Comment by wsalesky** [comment]
Done
