### ISSUE TITLE
Add material support, form, and extent values to About this Manuscript section

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#57]
Could we add the material support, form, and extent values to the About this Manuscript section (cf. https://docs.google.com/document/d/1wXhlqdGbqurhWCSdzGp74NIoXbflFhrrGcHjQdqMmKM/edit and #40 )

Example record: https://bl.vuexistapps.us/manuscript/142

These would be added after the script information:

Current:

"Unspecified Syriac script (multiple hands)."

New:

"Unspecified Syriac script (multiple hands).  Parchment Codex, 312 leaves."

----

Notes, xpaths, etc.

1. Material Support
    - xpath: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/@material`
    - The following table gives the label to display based on these values:
"perg" --> "Parchment"
"chart" --> "Paper"
"mixed" --> "Mixed Material"

2. Form
    - Xpath: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/@form`
    - The values will have to be capitalized

3. Extent
    - Xpath: `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/objectDesc/supportDesc/extent/measure[@type="composition"]/@quantity`
    - The attribute only has the number, so "leaves" will need to be supplied by the App. If possible, could you have a test that supplies "leaf" when the `@quantity` is 1, e.g. "1 leaf", and "leaves" otherwise?
    - Note: this is not fully implemented in all data, but https://bl.vuexistapps.us/manuscript/142 can be used as an example.

----

For reference, the full "About this Manuscript" section should look like this:

```
URI: http://syriaca.org/manuscript/142
Description based on Wright LXXXV  (I:60-61)
Date: Early in the 12th century
Unspecified Syriac script (multiple hands). Parchment Codex, 130 leaves.
Features: Decoration
Wright's Subject Classification: New Testament
```

@davidamichelson please add to/revise this issue if I've missed anything

**Comment by wsalesky** [comment]
Fixed
