### ISSUE TITLE
Some manuscripts still displaying "Material", "Extent", and "Layout" fields

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#58]
Related to #37 where we wanted to suppress all elements in the `physDesc/objectDesc`. It looks like some records still have these displayed? (App version 2.03)

Here are a few examples:

https://bl.vuexistapps.us/manuscript/142
https://bl.vuexistapps.us/manuscript/403

I'm not sure why these are still showing up just in certain cases? Let me know if it looks like a data issue

**Comment by wsalesky** [comment]
Fixed
