### ISSUE TITLE
Display all descendant text content in `//physDesc/p` and `//handNote`

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#59]
In several cases it looks like we are only displaying the immediate child text rather than all descendant texts. Below are two cases, with examples:

1. `//physDesc/p`
    - example: https://bl.vuexistapps.us/manuscript/205
    - We are not displaying the `//physDesc/p/locus/text()` content in this example
    - In the "Physical Description" paragraph we have "...volume, and two leaves are missing after There are from...", which should become "...volume, and two leaves are missing after fol. 3. There are from..."

2. `//handNote`
    - example: https://bl.vuexistapps.us/manuscript/405
    - In the second hand note ("Hand Note 2"), we are not displaying the `//handNote/locus/text()` content
    - "Foll.,,,,,,,,,,, and are in a plain, legible hand of the xth or xith cent. The later scribe has added foll.. " should become "Foll. 1-8, 19, 28, 29, 38, 59, 68, 89, 90, 97, 98, 100, 107, 125, 126, and 131 are in a plain, legible hand of the xth or xith cent. The later scribe has added foll. 132—171."

(This is App version 2.03)

**Comment by wsalesky** [comment]
@wlpotter Thanks this was due to the special handling for locus, it is working now.
