### ISSUE TITLE
`//handNote/date` and `//handNote/origDate` should be displayed in-line

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#60]
This may be resolved by #59 , but when we have a `date` or `origDate` element that is a child of the `handNote`, it is displayed with its own label on a new line. Example: https://bl.vuexistapps.us/manuscript/142

We'd like this to display in-line, without a label.

Current:

```
Hand 1 (major, Unvocalized Syriac of any variety or period) : This volume is written in a rather inelegant hand, apparently that ofSamuel bar Cyriacus(seeAdd. 14,679),
Date: early in the 12th century
. 
```

Updated:

```
Hand 1 (major, Unvocalized Syriac of any variety or period) : This volume is written in a rather inelegant hand, apparently that ofSamuel bar Cyriacus(seeAdd. 14,679), early in the 12th century.
```

Note: the whitespace issues in the rest of the hand note are another matter, and may be a data issue. I need to look into that separately

**Comment by wsalesky** [comment]
fixed
