### ISSUE TITLE
Labels for `handNote/@script` should match the "About this manuscript" section

### ISSUE THREAD

**Issue by wlpotter** [srophe/britishLibrary#62]
In the "About this manuscript" section (cf. #40 and https://docs.google.com/document/d/1wXhlqdGbqurhWCSdzGp74NIoXbflFhrrGcHjQdqMmKM/edit), the `//handNote/@script` values, which are ISO language codes, are mapped to a set of labels:

"syr"= Unspecified Syriac script
"syr-Syre"= Estrangela script
"syr-Syrj”= West Syriac script
"syr-Syrn”= East Syriac script
"syr-x-syrm”= Melkite Syriac script
"grc”= Greek
"ar-Syrc”= Arabic Garshuni script
“ar” = Unspecified Arabic script

We'd like to use these same labels in the "Hand" notes section. Example record: https://bl.vuexistapps.us/manuscript/142

In the "About" section, the label is "Unspecified Syriac script" but in the "Hand 1" section it is "Unvocalized Syriac of any variety or period". In both cases, we'd like to use the labels listed above:

Current: "Hand 1 (major, Unvocalized Syriac of any variety or period)"
Updated: "Hand 1 (major, Unspecified Syriac script)"

**Comment by wsalesky** [comment]
Fixed
