### ISSUE TITLE
Extra white spaces in concatenations

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#69]
See https://bl.vuexistapps.us/manuscript/10

Currently two white spaces between "CLXI" and"(1:101-108)":
"Description based on Wright CLXI  (1:101-108)"

Revise to delete one whitespace"
"Description based on Wright CLXI (1:101-108)"

Same issue (two white spaces) between Parchment  Codex in:
"East Syriac script (multiple hands). Parchment  Codex"

Revise to:
"East Syriac script (multiple hands). Parchment Codex"

**Comment by wsalesky** [comment]
Fixed
