### ISSUE TITLE
Delete trailing whitespaces in construction of handDesc/handNote

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#70]
In the construction of the handDesc/handNote there are two trailing whitespaces that should be deleted:
Example https://bl.vuexistapps.us/manuscript/10

Current:
Hand 1 (major, East Syriac script ) : The manuscript...

Revised:
Hand 1 (major, East Syriac script): The manuscript...

Delete space after script and after the closing parenthesis

**Comment by davidamichelson** [comment]
Also, please put the colon in bold (the same as the rest of the text before it).

**Comment by davidamichelson** [comment]
@wsalesky Thanks! Re-opening this issue as it seems to have come back in Version 2.04

See example: https://bl.vuexistapps.us/manuscript/10

Where "Hand 1 (major, East Syriac script ):" should be "Hand 1 (major, East Syriac script):"  {No space after "script"}

![Screen Shot 2023-04-28 at 3 36 05 PM](https://user-images.githubusercontent.com/3083773/235249478-fac1d12d-2abc-46b1-82d5-0904b8d224a2.png)

**Comment by wsalesky** [comment]
Done
