### ISSUE TITLE
Syriac Font Display Bug

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#79]
For some reason the HTML is using more than one Syriac font to display Syriac.

See this example from https://bl.vuexistapps.us/manuscript/10
Note that the first (bolder) font is the one our app is supposed to use. The second lighter font is probably Google's default Noto Unicode font being substituted for some reason.

We don't think this is a data issue, but it could be. You can easily see which syriac text is not working correctly by using the font changer button, the broken Syriac does not change font while the others do. This seems to be a problem in multiple records.

![Screen Shot 2023-04-28 at 2 22 49 PM](https://user-images.githubusercontent.com/3083773/235235149-27fc8815-d4f2-441c-adc8-dd78faf25d8a.png)

Thoughts @wsalesky ? We can discuss on Wed if that would help.

App version="2.04"

**Comment by wsalesky** [comment]
Fixed
