### ISSUE TITLE
Parent Elements by Grouping

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#8]
@wsalesky Here are the major discrete blocks of information to display:

/TEI/teiHeader/titleStmt, editionStmt, publicationStmt : will display together, currently is in the Cite This box

/TEI/teiHeader/profileDesc/textClass

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msIdentifier

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msContents

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/additions

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/p and objectDesc and handDesc and decoDesc (not all may be present)

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/history

/TEI/teiHeader/fileDesc/sourceDesc/msDesc/additional/listBibl/bibl

## IMPORTANT NOTE: Many XML files will have multiple msParts inside a single msDesc, in which case you could have:

/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/msIdentifier

/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/msContents

/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/physDesc/additions

/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/physDesc/p and objectDesc and handDesc and decoDesc (not all may be present)

/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/history

/TEI/teiHeader/fileDesc/sourceDesc/msDesc//msPart/additional/listBibl/bibl

**Comment by davidamichelson** [comment]
Lets discuss how the app needs to handle this nested information

**Comment by wlpotter** [comment]
Closing this as it is outdated. We can open additional issues as needed.
