### ISSUE TITLE
Add Browse Facet by Date

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#84]
Please add here: https://bl.vuexistapps.us/browse.html
Add to advanced search as a limit by date (enter start and stop dates to create range)

Will can you please research where the date info is located and put the paths here before we sent to Winona.

**Comment by davidamichelson** [comment]
Could this be a slider?

**Comment by wsalesky** [comment]
@davidamichelson  @wlpotter Added to v 2.20. Close if acceptable.

**Comment by davidamichelson** [comment]
Great work! There is one odd behavior in that some results drop out when the date range is increased! Notice what happens to the total count under "Material" when the date range is increased to 1909 (beyond our newest MS which is 1825).
![Screenshot 2023-09-18 at 1 48 21 PM](https://github.com/srophe/britishLibrary/assets/3083773/0df22439-8349-428b-bd13-919b6b93a27f)
![Screenshot 2023-09-18 at 1 48 13 PM](https://github.com/srophe/britishLibrary/assets/3083773/b51856e8-de48-42b3-b8cf-f8ad0b37d919)

**Comment by wlpotter** [comment]
Also, here is the additional XPath for the msParts (cf. #223 ): `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/history/origin/origDate`

These should have `@when`, `@notBefore`, and/or `@notAfter` attributes with ISO dates

**Comment by wsalesky** [comment]
Please check the updates.

**Comment by wlpotter** [comment]
Yes, there appear to be some data issues causing this. We have a data issue (https://github.com/srophe/britishLibrary-data/issues/529) for normalizing origDates, so I'll prioritize that one, which should hopefully resolve some of these issues.

**Comment by wsalesky** [comment]
@wlpotter should we close this? Or leave open to test after data updates?

**Comment by wlpotter** [comment]
I think we can close this. I'll make a note in the data issue to test the facets once those updates are done
