### ISSUE TITLE
Change Live Link to Place URI after "Origin" in Record Page

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#85]
Currently, the record page has "Origin: {Prose with link to Syriaca.org Place URI}"

Example: https://bl.vuexistapps.us/manuscript/10

Origin: [the convent of Mār Gabriel (also called the convent of the Confessors) near Harrān](https://syriaca.org/place/226) 

Please change this so that the underlying live link instead points to a search result within the app:

Corrected:
Origin: [the convent of Mār Gabriel (also called the convent of the Confessors) near Harrān](Search result for URI https://syriaca.org/place/226 in the XML of all records)

**Comment by davidamichelson** [comment]
/TEI/teiHeader/fileDesc/sourceDesc/msDesc/history/origin/origPlace/@ref

**Comment by davidamichelson** [comment]
FYI it is possible that there might be multiple origPlace/@ref or even origPlace siblings, so please check all.

**Comment by wsalesky** [comment]
Link added. Link functionality will come when I address search bugs. #117
