### ISSUE TITLE
Change hardcoded puncation in the HTML

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#86]
Currently the line "East Syriac script (multiple hands). Parchment Codex" has a hard coded period (".") between the hands and the parchment.

Please change this "." to this character "܀" (U+0700)

Example https://bl.vuexistapps.us/manuscript/10 
Original:
East Syriac script (multiple hands). Parchment Codex

Revised:
East Syriac script (multiple hands) ܀ Parchment Codex

**Note:** this change both replaces the period and introduces a white space before the Syriac U+700 character.

**Comment by wsalesky** [comment]
Done
