### ISSUE TITLE
Create Browse for " Wright's Subject Classification"

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#88]
@wlpotter Please add the xpath and details for Winona and then reassign. Thanks

**Comment by wlpotter** [comment]
Data is in `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/head/listRelation[@type="Wright-BL-Taxonomy"]/relation[@name="dcterms:type"]`

- `@passive` contains the term to facet on, e.g. "#bible-punctuation"
- `./desc/text()` contains a human-readable label for the taxonomy term

**Comment by wlpotter** [comment]
Each record contains a `/TEI/teiHeader/encodingDesc/classDecl/taxonomy[@xml:id="Wright-BL-Taxonomy"]`, with the tei:category elements that the `//head/listRelation` refers to.

@wsalesky If it would be helpful, we can create a standalone index page for this taxonomy (similar to what we did with the historical periods for Caesarea, https://github.com/srophe/caesarea/blob/master/documentation/caesarea-maritima-historical-era-taxonomy.xml). Let me know and I can create a file for the Wright taxonomy

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Can you clarify what this is? A new tab on the browse page? A new facet on the browse page? 
Thanks!

**Comment by davidamichelson** [comment]
This is a new facet on the browse page, to the left

**Comment by wsalesky** [comment]
@davidamichelson  @wlpotter Added to v 2.20. Close if acceptable.

**Comment by wlpotter** [comment]
Here is the additional XPath for the msParts 9cf. #223 ): `/TEI/teiHeader/fileDesc/sourceDesc/msDesc/msPart/head/listRelation[@type="Wright-BL-Taxonomy"]/relation[@name="dcterms:type"]`
