### ISSUE TITLE
Trailing whitespace after dates

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#90]
@wsalesky There are extra trailing whitespaces after the dates in the Physical Description Hand Notes.
Example: https://bl.vuexistapps.us/manuscript/10
Current:
``` Hand 1 (major, East Syriac script ): The manuscript is written in a small, Nestorian character, and dated A. Gr. 1210 , A.D. 899 . ```
Revised:
``` Hand 1 (major, East Syriac script ): The manuscript is written in a small, Nestorian character, and dated A. Gr. 1210, A.D. 899. ```
Note: remove space after 1210 and 899.
Path: /TEI/teiHeader/fileDesc/sourceDesc/msDesc/physDesc/handDesc/handNote/date
Version: 2.04

**Comment by wsalesky** [comment]
Done.
