### ISSUE TITLE
Manuscript Contents Changes to msItem children rubric and final rubric and note

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#93]
For msItem/rubric please put this on a new line with the label "Title" and change msItem/finalRubric to "Subscription".

Lastly for the msItem/note elements, we would love to do something but are not sure what. They could be labelled "note" but is there something else that could be done visually? Do you have any ideas @wsalesky ? Could they be grouped? Or a box?

example: https://bl.vuexistapps.us/manuscript/10

current:
**Item 1:** foll. 1b-303b The Book of the Collections of the Vowel-points and Readings, which are in the Holy Scriptures ܒܐܲܠܵܗܵܐ ܡܫܲܪܸܝܢܲܢ : ܟ݂ܕ ܠܗ ܠܐܲܠܵܗܐ ܥ̣ܠܬ݂ܵܐ ܣܵܝܡܝ̣ܢܲܢ܆ ܐܲܝܟܲܢܵܐ ܕܥ̣ܠ ܬܘܼܟ݂ܠܵܢܗ ܡܫܲܪܝܢܢ܆ ܐܲܝܟܲܢܵܐ ܕܥ̣ܠ ܬܘܼܟ݂ܠܵܢܹܗ ܢܫ̣ܠܸܡ.. ܘܟ݂ܕ ܥ̣ܠ ܬܘܼܟ݂ܠܵܢܗ ܡܫܲܪܝܢܢ܆ ܟܵܬ݂ܒܝܢܢ ܟܬ݂ܒܐ ܕܠܘܼܩܵܛܐ ܕܲܫܡܵܗܐ ܘܕܲܩܪ̈ܵܝܵܬ݂ܐ. ܕܐܝ̇ܬ ܒܨܘܪܬ ܟܬ݂ܵܒ
**Desinit:** ܫܠܸܡ ܠܡܸܟ̣ܬ݂̈ܒ݂ ܫܡܵܗ̈ܐ ܥܲܣܩ̈ܐ ܘܲܩܪ̈ܝܵܬ݂ܐ ܕܡ̣ܢ ܟܠܗܘܿܢ ܟܬ݂ܵܒ݂̈ܐ ܕܨܘܼܪܸܬ ܟܬ݂ܵܒ݂ ܕܥܲܬ݁ܝ̣ܩܬ݁ܐ ܘܕܲܚܕܲܬ݁ܐ ܕܗ̇ܘܐ ܣܵܟ݂ܐ ܕܟ݂ܠܗܘ݀ܢ ܨܚܵܚܲܝܗܘܿܢ ܒܲܟ݂ܢܝ̣ܫܘܼ ܫܹܬ݂ܡܵܐܐ ܘܚܲܡܸܫܬ̣̈ܥܣܲܪ ܨܚܵܚ̈ܐ ܕܐܘܿܪܵܝܬ݁ܐ ܡܵܐܐ ܘܥܹܣܪܝ̣ܢ ܘܸܫܬ݁ܐ ܕܒ̣ܝܹܬ ܡܵܘ̈ܬ݁ܒܹܐ ܟܠܗ ܡܵܐܐ ܘܸܫܬ݁ܝ̣ܢ ܘܐܲܪܒ݁ܥܐ. ܕܕܵܘܝ̣ܕ̣ ܥܹܣܪܝ̣ܢ ܘܬܸܫܥܵܐ ܕܲܢܒ̣ܝ̈ܐ ܡܵܐܐ ܘܲܬ̣ܠܬ݂ܝ̣ܢ ܘܚ̣ܕ. ܕ̇ܚܕ݂ܬ݁ܐ ܡܵܐܐ ܘܹܫܬ݁ܝ̣ܢ ܘܚܲܡܫܵܐ. 
The term Bēth-Mautbē, found in the subscription, includes the Book of Joshua, Judges, Samuel, Kings, Proverbs, Ecclesiasticus, Ecclesiastes, Ruth, the Song of Songs, and Job. See Add. 14,440 .
It may be not inaptly described as a sort of Syriac Masora, exhibiting all the more difficult words and sentences of the Biblical text, with the appropriate vowels and signs of punctuation, and accompanied by marginal notes, both critical and explanatory.
On works of this class see the treatise of M. l’Abbé Martin, “Tradition Karkaphienne, on a la Massore chez les Syriens,” in the Journal Asiatique for Oct.-Nov., 1869, no. 54, p.245. He has some remarks on Add. 12,138, at p. 337, foll.
The Canon of Scripture, as recognized in this work, comprises the following books in the order in which they are here enumerated. 
revised:
**Item 1 (fol. 1b):** The Book of the Collections of the Vowel-points and Readings, which are in the Holy Scriptures
**Title:** ܒܐܲܠܵܗܵܐ ܡܫܲܪܸܝܢܲܢ : ܟ݂ܕ ܠܗ ܠܐܲܠܵܗܐ ܥ̣ܠܬ݂ܵܐ ܣܵܝܡܝ̣ܢܲܢ܆ ܐܲܝܟܲܢܵܐ ܕܥ̣ܠ ܬܘܼܟ݂ܠܵܢܗ ܡܫܲܪܝܢܢ܆ ܐܲܝܟܲܢܵܐ ܕܥ̣ܠ ܬܘܼܟ݂ܠܵܢܹܗ ܢܫ̣ܠܸܡ.. ܘܟ݂ܕ ܥ̣ܠ ܬܘܼܟ݂ܠܵܢܗ ܡܫܲܪܝܢܢ܆ ܟܵܬ݂ܒܝܢܢ ܟܬ݂ܒܐ ܕܠܘܼܩܵܛܐ ܕܲܫܡܵܗܐ ܘܕܲܩܪ̈ܵܝܵܬ݂ܐ. ܕܐܝ̇ܬ ܒܨܘܪܬ ܟܬ݂ܵܒ
**Subscription:** ܫܠܸܡ ܠܡܸܟ̣ܬ݂̈ܒ݂ ܫܡܵܗ̈ܐ ܥܲܣܩ̈ܐ ܘܲܩܪ̈ܝܵܬ݂ܐ ܕܡ̣ܢ ܟܠܗܘܿܢ ܟܬ݂ܵܒ݂̈ܐ ܕܨܘܼܪܸܬ ܟܬ݂ܵܒ݂ ܕܥܲܬ݁ܝ̣ܩܬ݁ܐ ܘܕܲܚܕܲܬ݁ܐ ܕܗ̇ܘܐ ܣܵܟ݂ܐ ܕܟ݂ܠܗܘ݀ܢ ܨܚܵܚܲܝܗܘܿܢ ܒܲܟ݂ܢܝ̣ܫܘܼ ܫܹܬ݂ܡܵܐܐ ܘܚܲܡܸܫܬ̣̈ܥܣܲܪ ܨܚܵܚ̈ܐ ܕܐܘܿܪܵܝܬ݁ܐ ܡܵܐܐ ܘܥܹܣܪܝ̣ܢ ܘܸܫܬ݁ܐ ܕܒ̣ܝܹܬ ܡܵܘ̈ܬ݁ܒܹܐ ܟܠܗ ܡܵܐܐ ܘܸܫܬ݁ܝ̣ܢ ܘܐܲܪܒ݁ܥܐ. ܕܕܵܘܝ̣ܕ̣ ܥܹܣܪܝ̣ܢ ܘܬܸܫܥܵܐ ܕܲܢܒ̣ܝ̈ܐ ܡܵܐܐ ܘܲܬ̣ܠܬ݂ܝ̣ܢ ܘܚ̣ܕ. ܕ̇ܚܕ݂ܬ݁ܐ ܡܵܐܐ ܘܹܫܬ݁ܝ̣ܢ ܘܚܲܡܫܵܐ. 
**Notes:**
- The term Bēth-Mautbē, found in the subscription, includes the Book of Joshua, Judges, Samuel, Kings, Proverbs, Ecclesiasticus, Ecclesiastes, Ruth, the Song of Songs, and Job. See Add. 14,440 .
- It may be not inaptly described as a sort of Syriac Masora, exhibiting all the more difficult words and sentences of the Biblical text, with the appropriate vowels and signs of punctuation, and accompanied by marginal notes, both critical and explanatory.
- On works of this class see the treatise of M. l’Abbé Martin, “Tradition Karkaphienne, on a la Massore chez les Syriens,” in the Journal Asiatique for Oct.-Nov., 1869, no. 54, p.245. He has some remarks on Add. 12,138, at p. 337, foll.
- The Canon of Scripture, as recognized in this work, comprises the following books in the order in which they are here enumerated.

**Comment by wsalesky** [comment]
@davidamichelson I made some changes. Let me know what you think.

**Comment by davidamichelson** [comment]
Is it formatting the folio numbers like this: **Item 1 (fol. 1b):** ? I am not seeing it on the server version 2.05

**Comment by davidamichelson** [comment]
@wsalesky For some reason the msItem/finalRubric is doubled in the HTML for this record (but only the English one). It is not doubled in the XML just the HTML.

https://bl.vuexistapps.us/manuscript/10

<img width="1349" alt="Screen Shot 2023-05-03 at 9 49 04 PM" src="https://user-images.githubusercontent.com/3083773/236101092-426a3f9f-5350-4740-b524-37636b3fef34.png">

**Comment by wsalesky** [comment]
Fixed
