### ISSUE TITLE
HTML rendering of msItem/title/@ref=Syriaca.orgURI

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#94]
When a msItem/title/ has an @ref=Syriaca.orgURI, please construct a URL that is is an advanced search return for that Syriaca URI within the BL app.

This is a change from the current version which takes you out of the app and to the Syriaca.org page (example http://syriaca.org/work/9628)

Instead please construct something like this that returns results from within msItem/title/@ref:
https://bl.vuexistapps.us/search.html?title=http://syriaca.org/work/9628

**Comment by davidamichelson** [comment]
Additional note. When a title has a person URI in it please ignore and do not display in the HTML.

**Comment by wsalesky** [comment]
@davidamichelson what should the search result return?

**Comment by wsalesky** [comment]
@davidamichelson the link is in place. The search function will come with #117  work.
