### ISSUE TITLE
Display for msItem/author

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#95]
example: https://bl.vuexistapps.us/manuscript/1043

When there is an msItem/author please insert that in-line before the first msItem/title

Please note that there are title changes in issue #92 that apply here too

So format the entry this way:

Current:
Item 1: (defective) Foll. 1a-158 [Severus](http://syriaca.org/person/51) The Hymns of [Severus](http://syriaca.org/person/51), etc., in number 383.

Revised:
**Item 1 (Fol. 1a):** [Severus](https://bl.vuexistapps.us/search.html?author=http://syriaca.org/person/51). The Hymns of Severus, etc., in number 383. [defective]

**Comment by davidamichelson** [comment]
If there are multiple authors (msItem/author) please separate by comma.

**Comment by wsalesky** [comment]
done
