### ISSUE TITLE
msItem/quote

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary#96]
Please label msItem/quote as "**Excerpt (fol. 6a):**" (do start a new line for each quote)

Example: https://bl.vuexistapps.us/manuscript/1113

Current:
 “ܡ܏ܐܡ ܩܕܡܝܐ. ܥܠ ܡܛܟܣܘܬ ܙܘ̈ܥܐ ܕܕܘܼܪܫܐ ܦܓܪܢܝ̇ܐ ܘܒܗ ܐܝ̣ܬ ܩܦ̣̈ܠܐܐ ܬܫܥܐ. ” 

Revised:
**Excerpt (fol. 6a):**  ܡ܏ܐܡ ܩܕܡܝܐ. ܥܠ ܡܛܟܣܘܬ ܙܘ̈ܥܐ ܕܕܘܼܪܫܐ ܦܓܪܢܝ̇ܐ ܘܒܗ ܐܝ̣ܬ ܩܦ̣̈ܠܐܐ ܬܫܥܐ.

**Comment by davidamichelson** [comment]
Notes: the quotation marks are removed and in theory there should only be a one left to right whitespace after "):"

**Comment by davidamichelson** [comment]
Please use msItem/quote/locus/@from to construct the location. If there is no msItem/quote/locus, do not add the parentheses.

**Comment by wsalesky** [comment]
Done
